// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using Proj_ProspEco.Data;

#nullable disable

namespace Proj_ProspEco.Migrations
{
    [DbContext(typeof(ProspEcoDbContext))]
    [Migration("20241122173747_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Proj_ProspEco.Models.Aparelho", b =>
                {
                    b.Property<int>("Id_aparelho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Id_aparelho");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_aparelho"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar2(50)")
                        .HasColumnName("ds_nome");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Id_usuario");

                    b.HasKey("Id_aparelho");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TB_Aparelho");
                });

            modelBuilder.Entity("Proj_ProspEco.Models.BandeiraTarifaria", b =>
                {
                    b.Property<int>("Id_bandeira")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Id_bandeira");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_bandeira"));

                    b.Property<DateTime>("DataVigencia")
                        .HasColumnType("DATE")
                        .HasColumnName("dt_vigencia");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar2(50)")
                        .HasColumnName("ds_bandeira");

                    b.HasKey("Id_bandeira");

                    b.ToTable("TB_BandeiraTarifaria");
                });

            modelBuilder.Entity("Proj_ProspEco.Models.Conquista", b =>
                {
                    b.Property<int>("Id_conquista")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Id_conquista");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_conquista"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar2(100)")
                        .HasColumnName("ds_conquista");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Id_usuario");

                    b.HasKey("Id_conquista");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TB_Conquista");
                });

            modelBuilder.Entity("Proj_ProspEco.Models.Meta", b =>
                {
                    b.Property<int>("Id_meta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Id_meta");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_meta"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar2(100)")
                        .HasColumnName("ds_meta");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Id_usuario");

                    b.HasKey("Id_meta");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TB_Meta");
                });

            modelBuilder.Entity("Proj_ProspEco.Models.Notificacao", b =>
                {
                    b.Property<int>("Id_notificacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Id_notificacao");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_notificacao"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar2(255)")
                        .HasColumnName("ds_notificacao");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Id_usuario");

                    b.HasKey("Id_notificacao");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TB_Notificacao");
                });

            modelBuilder.Entity("Proj_ProspEco.Models.Recomendacao", b =>
                {
                    b.Property<int>("Id_recom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Id_recom");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_recom"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar2(255)")
                        .HasColumnName("ds_recomendacao");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Id_usuario");

                    b.HasKey("Id_recom");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TB_Recomendacao");
                });

            modelBuilder.Entity("Proj_ProspEco.Models.RegistroConsumo", b =>
                {
                    b.Property<int>("Id_registro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Id_registro");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_registro"));

                    b.Property<int>("AparelhoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Id_aparelho");

                    b.Property<int>("BandeiraId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Id_bandeira");

                    b.Property<decimal>("Consumo")
                        .HasColumnType("NUMBER(10, 2)")
                        .HasColumnName("nr_consumo");

                    b.HasKey("Id_registro");

                    b.HasIndex("AparelhoId");

                    b.HasIndex("BandeiraId");

                    b.ToTable("TB_RegistroConsumo");
                });

            modelBuilder.Entity("Proj_ProspEco.Models.Usuario", b =>
                {
                    b.Property<int>("Id_usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Id_usuario");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_usuario"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar2(50)")
                        .HasColumnName("ds_email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar2(100)")
                        .HasColumnName("ds_nome");

                    b.Property<decimal>("PontuacaoEconom")
                        .HasColumnType("NUMBER(10,2)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar2(50)")
                        .HasColumnName("ds_senha");

                    b.HasKey("Id_usuario");

                    b.ToTable("TB_Usuario");
                });

            modelBuilder.Entity("Proj_ProspEco.Models.Aparelho", b =>
                {
                    b.HasOne("Proj_ProspEco.Models.Usuario", "Usuario")
                        .WithMany("Aparelhos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Proj_ProspEco.Models.Conquista", b =>
                {
                    b.HasOne("Proj_ProspEco.Models.Usuario", "Usuario")
                        .WithMany("Conquistas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Proj_ProspEco.Models.Meta", b =>
                {
                    b.HasOne("Proj_ProspEco.Models.Usuario", "Usuario")
                        .WithMany("Metas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Proj_ProspEco.Models.Notificacao", b =>
                {
                    b.HasOne("Proj_ProspEco.Models.Usuario", "Usuario")
                        .WithMany("Notificacoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Proj_ProspEco.Models.Recomendacao", b =>
                {
                    b.HasOne("Proj_ProspEco.Models.Usuario", "Usuario")
                        .WithMany("Recomendacoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Proj_ProspEco.Models.RegistroConsumo", b =>
                {
                    b.HasOne("Proj_ProspEco.Models.Aparelho", "Aparelho")
                        .WithMany("RegistrosConsumo")
                        .HasForeignKey("AparelhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proj_ProspEco.Models.BandeiraTarifaria", "BandeiraTarifaria")
                        .WithMany()
                        .HasForeignKey("BandeiraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aparelho");

                    b.Navigation("BandeiraTarifaria");
                });

            modelBuilder.Entity("Proj_ProspEco.Models.Aparelho", b =>
                {
                    b.Navigation("RegistrosConsumo");
                });

            modelBuilder.Entity("Proj_ProspEco.Models.Usuario", b =>
                {
                    b.Navigation("Aparelhos");

                    b.Navigation("Conquistas");

                    b.Navigation("Metas");

                    b.Navigation("Notificacoes");

                    b.Navigation("Recomendacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
